package cn.lunadeer.dominion.utils.configuration;

import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Marker interface for configuration files.
 * <p>
 * The items in the configuration file should be public fields.
 * <p>
 * The constructor should be public and have no parameters.
 * <p>
 * Ported from Bukkit YamlConfiguration to SnakeYAML for Fabric.
 */
public abstract class ConfigurationFile extends ConfigurationPart {

    private Map<String, Object> yamlData = new LinkedHashMap<>();

    public Map<String, Object> getYamlData() {
        return yamlData;
    }

    public void setYamlData(Map<String, Object> yamlData) {
        this.yamlData = yamlData;
    }

    /**
     * Get a value from the yaml data by dotted key path.
     * Returns null if the key does not exist.
     */
    public Object get(String key) {
        String[] parts = key.split("\\.");
        Map<String, Object> current = yamlData;
        for (int i = 0; i < parts.length - 1; i++) {
            Object next = current.get(parts[i]);
            if (next instanceof Map) {
                @SuppressWarnings("unchecked")
                Map<String, Object> nextMap = (Map<String, Object>) next;
                current = nextMap;
            } else {
                return null;
            }
        }
        return current.get(parts[parts.length - 1]);
    }

    /**
     * Set a value in the yaml data by dotted key path.
     * Creates intermediate maps as needed.
     */
    public void set(String key, Object value) {
        String[] parts = key.split("\\.");
        Map<String, Object> current = yamlData;
        for (int i = 0; i < parts.length - 1; i++) {
            Object next = current.get(parts[i]);
            if (next instanceof Map) {
                @SuppressWarnings("unchecked")
                Map<String, Object> nextMap = (Map<String, Object>) next;
                current = nextMap;
            } else {
                Map<String, Object> newMap = new LinkedHashMap<>();
                current.put(parts[i], newMap);
                current = newMap;
            }
        }
        current.put(parts[parts.length - 1], value);
    }

    /**
     * Check if a key exists in the yaml data by dotted key path.
     */
    public boolean contains(String key) {
        String[] parts = key.split("\\.");
        Map<String, Object> current = yamlData;
        for (int i = 0; i < parts.length - 1; i++) {
            Object next = current.get(parts[i]);
            if (next instanceof Map) {
                @SuppressWarnings("unchecked")
                Map<String, Object> nextMap = (Map<String, Object>) next;
                current = nextMap;
            } else {
                return false;
            }
        }
        return current.containsKey(parts[parts.length - 1]);
    }

    /**
     * Get a boolean value from the yaml data.
     */
    public boolean getBoolean(String key, boolean defaultValue) {
        Object val = get(key);
        if (val instanceof Boolean) {
            return (Boolean) val;
        }
        return defaultValue;
    }

    /**
     * Get a string value from the yaml data.
     */
    public String getString(String key) {
        Object val = get(key);
        return val != null ? val.toString() : null;
    }

    /**
     * Get a section (sub-map) from the yaml data.
     * Returns null if the key does not exist or is not a map.
     */
    @SuppressWarnings("unchecked")
    public Map<String, Object> getConfigurationSection(String key) {
        Object val = get(key);
        if (val instanceof Map) {
            return (Map<String, Object>) val;
        }
        return null;
    }

    /**
     * Create an empty section at the given key.
     */
    public void createSection(String key) {
        if (!contains(key)) {
            set(key, new LinkedHashMap<String, Object>());
        }
    }

    /**
     * Get all keys at the top level of the yaml data.
     */
    public java.util.Set<String> getKeys(boolean deep) {
        return yamlData.keySet();
    }

    public void save(File file) throws Exception {
        DumperOptions options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setPrettyFlow(true);
        options.setWidth(250);
        Yaml yaml = new Yaml(options);
        try (Writer writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
            writer.write("# This file is auto-generated by Dominion.\n");
            writer.write("# Editing by hand is allowed but may be overwritten.\n\n");
            yaml.dump(yamlData, writer);
        }
    }
}
